site_name: Obtainium Wiki
repo_url: https://github.com/ImranR98/Obtainium
site_description: Help page for Obtainium
docs_dir: pages
site_author: ImranR98
edit_uri: https://github.com/ImranR98/Obtainium-Wiki/edit/main/pages/

nav:
  - Home: index.md
  - UI Overview: ui_overview.md
  - How Apps are Tracked: app_tracking.md
  - App Sources: sources.md

theme:
  name: material
  logo: assets/logo.png
  custom_dir: pages/overrides
  favicon: https://raw.githubusercontent.com/ImranR98/Obtainium/main/assets/graphics/icon_small.png

  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.footer

  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: simple/github
      link: https://github.com/ImranR98/
      name: GitHub
    - icon: simple/mastodon
      link: https://freeradical.zone/@imran
      name: Mastodon
    - icon: simple/kofi
      link: https://ko-fi.com/imranr
      name: Ko-fi
    - icon: material/heart
      link: https://github.com/sponsors/ImranR98
      name: GitHub Sponsors
    - icon: material/web
      link: https://imranr.dev/
      name: Website

  translations:
    made_by: Made by
    open_an_issue: Open an Issue
    crowdsourced_app_configurations: Crowdsourced App Configurations
    obtainium_website: Obtainium Website
    made_with: Made with
    missing_translation: 'This page has not yet been translated. You are viewing the English version.'
    help_translate: 'Help translate this page'

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: 🇬🇧 English
          # site_name for English is at the top
          # site_description for English is at the top
          # nav_translations for English are under the main nav key
          # extra translations for English are under the main extra key

        - locale: de
          name: 🇩🇪 Deutsch
          site_name: "Obtainium Wiki"
          site_description: "Hilfeseite für Obtainium"
          nav_translations:
            UI Overview: Übersicht User Interface
            How Apps are Tracked: Wie Apps nachverfolgt werden

        - locale: zh
          name: 🇨🇳 简体中文（中国大陆）
          site_name: "Obtainium Wiki"
          site_description: "Obtainium 帮助与支持"
          nav_translations:
            Home: 首页
            UI Overview: 界面概述
            How Apps are Tracked: 如何跟踪应用
            App Sources: 应用源
          extra:
            social:
              - icon: simple/github
                link: https://github.com/ImranR98/
                name: GitHub
              - icon: simple/mastodon
                link: https://freeradical.zone/@imran
                name: Mastodon
              - icon: simple/kofi
                link: https://ko-fi.com/imranr
                name: Ko-fi
              - icon: material/heart
                link: https://github.com/sponsors/ImranR98
                name: 通过 GitHub Sponsors 赞助
              - icon: material/web
                link: https://imranr.dev/
                name: 官网
            translations:
              made_by: Made by
              open_an_issue: 创建 Issue
              crowdsourced_app_configurations: 众包应用配置
              obtainium_website: Obtainium 官网
              made_with: 采用
              missing_translation: '本页尚无简体中文（中国大陆）翻译，您正在浏览的是英文原文。'
              help_translate: '协助翻译'

        - locale: ru
          name: 🇷🇺 Русский
          site_description: "Справочная страница для Obtainium"
          nav_translations:
            Home: Главная
            UI Overview: Обзор интерфейса
            How Apps are Tracked: Как отслеживаются приложения
            App Sources: Источники приложений
          extra:
            translations:
              made_by: Сделано
              open_an_issue: Открыть отчёт о проблеме
              crowdsourced_app_configurations: Конфигурации приложений
              obtainium_website: Сайт Obtainium
              made_with: Сделано с помощью
              missing_translation: Эта страница ещё не переведена. Вы просматриваете версию на английском языке.
              help_translate: Помочь перевести эту страницу

        - locale: "null"
          name: ➕ Add
          build: false
          fixed_link: https://github.com/ImranR98/Obtainium-Wiki/blob/main/CONTRIBUTING.md

extra_css:
  - stylesheets/custom.css
